version: '3'
services:
  app:
    image: otel-native-graalvm
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4317"
      OTEL_EXPORTER_OTLP_HEADERS: "api-key=api-key"
      OTEL_SERVICE_NAME: "service-name"
      OTEL_EXPERIMENTAL_EXPORTER_OTLP_RETRY_ENABLED: true
      OTEL_METRIC_EXPORT_INTERVAL: 5000
      OTEL_RESOURCE_ATTRIBUTES: "service.instance.id=1235"
      OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: DELTA
      OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION: "BASE2_EXPONENTIAL_BUCKET_HISTOGRAM"
      OTEL_EXPORTER_OTLP_COMPRESSION: gzip
      OTEL_EXPERIMENTAL_RESOURCE_DISABLED_KEYS: "process.command_line,process.command_args"
      OTEL_LOGS_EXPORTER: "otlp"
    ports:
      - "8080:8080"
    depends_on:
      - collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.82.0
    volumes:
      - ./collector-spring-native-config.yaml:/collector-spring-native-config.yaml
    command: ["--config=/collector-spring-native-config.yaml"]
    expose:
      - "4317"
    ports:
      - "4317:4317"
